# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - horsescanfly-app

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://mcr.microsoft.com/
        username: ${{ secrets.AzureAppService_ContainerUsername_cd1832b2526e477e81413ed89ca14c03 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_9fe82e6a1b294e51bc89b685d8372900 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: mcr.microsoft.com/${{ secrets.AzureAppService_ContainerUsername_cd1832b2526e477e81413ed89ca14c03 }}/appsvc/staticsite:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'horsescanfly-app'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_ee1d163d19734105b084df1186d22d18 }}
        images: 'mcr.microsoft.com/${{ secrets.AzureAppService_ContainerUsername_cd1832b2526e477e81413ed89ca14c03 }}/appsvc/staticsite:${{ github.sha }}'